---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: 'Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit ou qui n"interagissent pas correctement avec elle. Examinez attentivement ces limitations.' 
---
= Limitations connues de Cloud Volumes ONTAP chez tous les fournisseurs de cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit ou qui n'interagissent pas correctement avec elle. Examinez attentivement ces limitations.

Les limitations suivantes s'appliquent à Cloud Volumes ONTAP chez tous les fournisseurs de cloud : AWS, Azure et Google Cloud.



== Fonctionnalités ONTAP non prises en charge

Les fonctionnalités suivantes ne sont pas prises en charge avec Cloud Volumes ONTAP:

* Déduplication en ligne au niveau agrégé
* Déduplication d'arrière-plan au niveau agrégé
* Centre de maintenance des disques
* Désinfection du disque
* Mise en miroir de FabricPool
* Fibre Channel (FC)
* Piscines Flash
* Volumes infinis
* Groupes d'interface
* Basculement LIF intra-nœud
* MetroCluster
* Vérification multi-administrateur
+
L'activation de la vérification multi-administrateur sur Cloud Volumes ONTAP entraînera une configuration non prise en charge.

* RAID4, RAID-DP, RAID-TEC (RAID0 est pris en charge)
* Processeur de services
* Modes SnapLock Compliance et Enterprise (seul Cloud WORM est pris en charge)
* SnapMirror Synchrone
* VLAN
* Disponibilité continue des PME (CA)
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Actions PME disponibles en continu"^] pour les opérations non perturbatrices ne sont pas prises en charge.





== Nombre maximal d'opérations de réplication simultanées

Le nombre maximal de transferts SnapMirror ou SnapVault simultanés pour Cloud Volumes ONTAP est de 100 par nœud, quel que soit le type d'instance ou le type de machine.



== Les instantanés du fournisseur de cloud ne doivent pas être utilisés pour vos plans de sauvegarde et de récupération

Vous ne devez pas utiliser les instantanés de votre fournisseur de cloud dans le cadre de votre plan de sauvegarde et de récupération des données Cloud Volumes ONTAP .  Vous devez toujours utiliser des copies ONTAP Snapshot ou des solutions de sauvegarde tierces pour sauvegarder et restaurer les données hébergées sur Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["Apprenez à utiliser la BlueXP backup and recovery pour sauvegarder et restaurer les données ONTAP"^] .


NOTE: Les points de cohérence ONTAP dans le système de fichiers WAFL déterminent la cohérence des données.  Seul ONTAP peut mettre en veille le système de fichiers WAFL pour effectuer une sauvegarde cohérente en cas de panne.



== Cloud Volumes ONTAP prend en charge uniquement les instances de machines virtuelles réservées et à la demande

Cloud Volumes ONTAP peut s'exécuter sur une instance de machine virtuelle réservée ou à la demande auprès de votre fournisseur de cloud.  Les autres types d’instances de VM ne sont pas pris en charge.



== Les solutions de gestion automatique des ressources des applications ne doivent pas être utilisées

Les solutions de gestion automatique des ressources d’application ne doivent pas gérer les systèmes Cloud Volumes ONTAP .  Cela peut entraîner une modification d’une configuration non prise en charge.  Par exemple, la solution peut modifier Cloud Volumes ONTAP en un type d’instance de machine virtuelle non pris en charge.



== Les mises à jour logicielles doivent être effectuées par BlueXP

Les mises à niveau de Cloud Volumes ONTAP doivent être effectuées à partir de BlueXP.  Vous ne devez pas mettre à niveau Cloud Volumes ONTAP à l’aide de System Manager ou de l’interface de ligne de commande.  Cela peut avoir un impact sur la stabilité du système.



== Le déploiement de Cloud Volumes ONTAP ne doit pas être modifié depuis la console de votre fournisseur de cloud

Les modifications apportées à une configuration Cloud Volumes ONTAP à partir de la console de votre fournisseur de cloud entraînent une configuration non prise en charge.  Toute modification apportée aux ressources Cloud Volumes ONTAP que BlueXP crée et gère peut avoir un impact sur la stabilité du système et sur la capacité de BlueXP à gérer le système.


NOTE: Après le déploiement initial, la modification du nom d’abonnement Azure utilisé pour les ressources Cloud Volumes ONTAP est prise en charge.



== Les disques et les agrégats doivent être gérés depuis BlueXP

Tous les disques et agrégats doivent être créés et supprimés directement depuis BlueXP.  Vous ne devez pas effectuer ces actions à partir d’un autre outil de gestion.  Cela peut avoir un impact sur la stabilité du système, entraver la possibilité d’ajouter des disques à l’avenir et potentiellement générer des frais de fournisseur de cloud redondants.



== Limitation de licence de SnapManager

Les licences par serveur SnapManager sont prises en charge avec Cloud Volumes ONTAP.  Les licences par système de stockage (suite SnapManager ) ne sont pas prises en charge.



== Limitations avec les agents et extensions tiers

Les agents tiers et les extensions de machine virtuelle ne sont pas pris en charge sur les instances de machine virtuelle Cloud Volumes ONTAP .
