---
sidebar: sidebar 
permalink: reference-provider-integrations.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support, SMB CA in CVO 
summary: Cette page décrit comment NetApp travaille avec les fournisseurs de cloud pour résoudre les problèmes qui pourraient survenir. 
---
= Collaboration avec les fournisseurs de cloud pour Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez comment NetApp collabore avec les fournisseurs de cloud pour résoudre les problèmes potentiels.



== Meilleures pratiques de soutien collaboratif

NetApp s'engage à fournir une assistance au titulaire de licence et déploiera des efforts commercialement raisonnables pour résoudre les problèmes d'assistance technique pour Cloud Volumes ONTAP lorsqu'ils sont signalés par le titulaire de licence.  NetApp et le fournisseur de cloud concerné n'ont aucune obligation de support direct envers les logiciels ou infrastructures sous licence de l'autre.

NetApp a mis en œuvre des outils visant à se connecter aux fournisseurs de cloud concernés sur les problèmes techniques des clients qui peuvent résulter des services des fournisseurs de cloud concernés.  Cependant, la meilleure façon de maintenir un flux de support transparent est pour les clients (i) de maintenir un contrat de support actuel avec NetApp et le fournisseur de cloud concerné et (ii) de coordonner des réunions d'escalade conjointes avec NetApp et le fournisseur de cloud concerné lorsque des problèmes techniques surviennent et que le client a besoin de clarté sur les produits ou services qui sont à l'origine de ces problèmes techniques.



== Événements de maintenance Azure

Microsoft planifie et annonce par programmation des événements de maintenance sur son infrastructure de machine virtuelle (VM) Azure qui peuvent affecter les machines virtuelles Cloud Volumes ONTAP .  Ces événements sont annoncés 15 minutes avant la fenêtre de maintenance.

La gestion spéciale des événements de maintenance est prise en charge pour les paires haute disponibilité (HA) Cloud Volumes ONTAP .  Pour maintenir la santé de l'application, nous effectuons une prise de contrôle préventive pour prioriser la stabilité, car toute perte de connectivité de plus de 15 secondes désactivera les capacités de basculement.

Lorsque la fenêtre de maintenance est annoncée, le nœud partenaire du nœud ciblé effectuera une prise de contrôle.  Une fois la maintenance terminée, un retour sera lancé.  Après le retour à la normale, la paire HA devrait revenir à un état sain.  Si cela ne se produit pas, contactez le support NetApp pour obtenir de l'aide.  Notez que les événements de maintenance ciblent l'une des machines virtuelles d'une paire HA à la fois, et généralement les deux nœuds sont ciblés dans une période de temps relativement courte.

Les clients CIFS/SMB utilisant des partages CIFS Cloud Volumes ONTAP non disponibles en continu subiront une perte de session lors d'une prise de contrôle et lors du retour de l'agrégat utilisé par la session à son nœud d'origine. Il s'agit d'une limitation imposée par le protocole CIFS/SMB lui-même. Vous pouvez utiliser des produits tiers approuvés pour éviter les problèmes liés à la prise de contrôle et à la restitution. Pour obtenir de l'aide, contactez le support NetApp .


NOTE: https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Actions PME disponibles en continu"^] pour les opérations non perturbatrices ne sont pas prises en charge dans Cloud Volumes ONTAP.
