---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: Ces limitations connues sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure. 
---
= Limitations connues de Cloud Volumes ONTAP dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues suivantes sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure.  Assurez-vous également de consulterlink:reference-limitations.html["Limitations de Cloud Volumes ONTAP chez tous les fournisseurs de cloud"] .



== Limitations liées à l'utilisation des extensions de machine virtuelle Azure

Cloud Volumes ONTAP ne prend pas en charge les extensions de machine virtuelle (VM) Azure, car elles affectent les opérations de gestion BlueXP . Lors du déploiement, BlueXP empêche l’installation de toute extension sur vos machines virtuelles. Si des extensions sont déjà installées sur vos machines virtuelles Cloud Volumes ONTAP existantes, contactez le support Microsoft Azure pour les supprimer. Pour obtenir des conseils, reportez-vous à l'article de la base de connaissances (KB) https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["Les extensions de gestion des machines virtuelles Azure peuvent-elles être installées dans Cloud Volume ONTAP?"^]

À partir du 14 juillet 2025, NetApp enverra des e-mails et vous avertira dans BlueXP si des extensions de machine virtuelle sont détectées sur vos machines virtuelles Cloud Volumes ONTAP .



== Limitations du cache Flash

Cloud Volumes ONTAP utilise le stockage NVMe local dans certains types de machines virtuelles comme _Flash Cache_.  Notez cette limitation :

* Le réchauffement du cache après un redémarrage n'est pas pris en charge.




== Limitations des déploiements à haute disponibilité

Les paires haute disponibilité (HA) ne sont pas prises en charge dans certaines régions.

https://bluexp.netapp.com/cloud-volumes-global-regions["Afficher la liste des régions Azure prises en charge"^] .



== Limitations des déploiements HA dans des zones de disponibilité uniques

À partir de Cloud Volumes ONTAP 9.15.1, vous pouvez déployer des instances de machine virtuelle (VM) en mode HA dans des zones de disponibilité uniques (AZ) dans Azure.  Pour plus d'informations sur les critères prenant en charge cette fonctionnalité, reportez-vous à https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["Déployer des paires HA dans des zones de disponibilité uniques dans Azure"^] .

Si la version de Cloud Volumes ONTAP est antérieure à 9.15.1 ou si l'une de ces conditions n'est pas remplie, le modèle de déploiement précédent utilisant des ensembles de disponibilité devient effectif.  Ceci s'applique uniquement aux configurations HA.
